project_name: hasuraf
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: hasuraf
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - tap:
      owner: sho-hata
      name: homebrew-hasuraf
    folder: Formula
    homepage: "https://github.com/sho-hata/hasuraf"
    description: "This command has a fzf-like UI that allows you to find and run the file version used by the hasura cli command."
    license: "MIT"
